import { toTimeStamp } from 'src/utils/utils';
import { Shop } from '../entities/shop.entity';

export class ShopDto {
    shop_id: string;
    user_id: string;
    shop_name: string;
    create_date: number;
    created_timestamp: number;
    title: string;
    announcement: string;
    currency_code: string;
    is_vacation: boolean;
    vacation_message: string;
    sale_message: string;
    digital_sale_message: string;
    update_date: number;
    updated_timestamp: number;
    listing_active_count: number;
    digital_listing_count: number;
    login_name: string;
    accepts_custom_requests: boolean;
    policy_welcome: string;
    policy_payment: string;
    policy_shipping: string;
    policy_refunds: string;
    policy_additional: string;
    policy_seller_info: string;
    policy_update_date: number;
    policy_has_private_receipt_info: boolean;
    has_unstructured_policies: boolean;
    policy_privacy: string;
    vacation_autoreply: string;
    url: string;
    image_url_760x100: string;
    num_favorers: number;
    languages: string[];
    icon_url_fullxfull: string;
    is_using_structured_policies: boolean;
    has_onboarded_structured_policies: boolean;
    include_dispute_form_link: boolean;
    is_direct_checkout_onboarded: boolean;
    is_etsy_payments_onboarded: boolean;
    is_calculated_eligible: boolean;
    is_opted_in_to_buyer_promise: boolean;
    is_shop_us_based: boolean;
    transaction_sold_count: number;
    shipping_from_country_iso: string;
    shop_location_country_iso: string;
    review_count: number;
    review_average: number;

    constructor(shop: Shop) {
        this.shop_id = shop.etsyShopId;
        this.user_id = shop.etsyUserId;
        this.shop_name = shop.etsyShopName;
        this.create_date = toTimeStamp(shop.etsyCreatedDate);
        this.created_timestamp = toTimeStamp(shop.etsyCreatedDate);
        this.title = shop.etsyShopName;
        this.announcement = '';
        this.currency_code = shop.currencyCode;
        this.is_vacation = Boolean(shop.isVacation);
        this.vacation_message = '';
        this.sale_message = '';
        this.digital_sale_message = '';
        this.update_date = toTimeStamp(shop.etsyUpdatedDate);
        this.updated_timestamp = toTimeStamp(shop.etsyUpdatedDate);
        this.listing_active_count = shop.listingActiveCnt || 0;
        this.digital_listing_count = 0;
        this.login_name = '';
        this.accepts_custom_requests = false;
        this.policy_welcome = '';
        this.policy_payment = '';
        this.policy_shipping = '';
        this.policy_refunds = '';
        this.policy_additional = '';
        this.policy_seller_info = '';
        this.policy_update_date = 0;
        this.policy_has_private_receipt_info = false;
        this.has_unstructured_policies = false;
        this.policy_privacy = '';
        this.vacation_autoreply = '';
        this.url = '';
        this.image_url_760x100 = shop.imageUrl || '';
        this.num_favorers = shop.favoritedCnt || 0;
        this.languages = [];
        this.icon_url_fullxfull = '';
        this.is_using_structured_policies = false;
        this.has_onboarded_structured_policies = false;
        this.include_dispute_form_link = false;
        this.is_direct_checkout_onboarded = false;
        this.is_etsy_payments_onboarded = false;
        this.is_calculated_eligible = false;
        this.is_opted_in_to_buyer_promise = false;
        this.is_shop_us_based = false;
        this.transaction_sold_count = 0;
        this.shipping_from_country_iso = '';
        this.shop_location_country_iso = '';
        this.review_count = shop.reviewCnt || 0;
        this.review_average = Number(shop.reviewAvg) || 0;
    }
}
